#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ahavrius <ahavrius@student.unit.ua>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/10/22 19:12:30 by ahavrius          #+#    #+#              #
#    Updated: 2018/10/22 19:18:42 by ahavrius         ###   ########.fr        #
#                                                                              #
#******************************************************************************#

FLAGS = -Wall -Wextra -Werror
NAME = ft_display_file

all : $(NAME)

$(NAME) :
	gcc $(FLAGS) -o $(NAME) *.c
clean :
	rm -f *.o
fclean : clean
	rm -f $(NAME)
re : fclean all